// flow-typed signature: 43a1c47b9ca23daceb032387653f86ee
// flow-typed version: <<STUB>>/html-minify_v^0.3.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-minify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-minify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-minify/lib/minify' {
  declare module.exports: any;
}

declare module 'html-minify/test/html_minify_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-minify/lib/minify.js' {
  declare module.exports: $Exports<'html-minify/lib/minify'>;
}
declare module 'html-minify/test/html_minify_test.js' {
  declare module.exports: $Exports<'html-minify/test/html_minify_test'>;
}
