// flow-typed signature: b40ae7781579df36c54e0deef1e16a8c
// flow-typed version: <<STUB>>/js-beautify_v^1.6.7/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-beautify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-beautify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-beautify/js/bin/css-beautify' {
  declare module.exports: any;
}

declare module 'js-beautify/js/bin/html-beautify' {
  declare module.exports: any;
}

declare module 'js-beautify/js/bin/js-beautify' {
  declare module.exports: any;
}

declare module 'js-beautify/js/index' {
  declare module.exports: any;
}

declare module 'js-beautify/js/lib/beautify-css' {
  declare module.exports: any;
}

declare module 'js-beautify/js/lib/beautify-html' {
  declare module.exports: any;
}

declare module 'js-beautify/js/lib/beautify' {
  declare module.exports: any;
}

declare module 'js-beautify/js/lib/cli' {
  declare module.exports: any;
}

declare module 'js-beautify/js/lib/unpackers/javascriptobfuscator_unpacker' {
  declare module.exports: any;
}

declare module 'js-beautify/js/lib/unpackers/myobfuscate_unpacker' {
  declare module.exports: any;
}

declare module 'js-beautify/js/lib/unpackers/p_a_c_k_e_r_unpacker' {
  declare module.exports: any;
}

declare module 'js-beautify/js/lib/unpackers/urlencode_unpacker' {
  declare module.exports: any;
}

declare module 'js-beautify/js/test/amd-beautify-tests' {
  declare module.exports: any;
}

declare module 'js-beautify/js/test/generated/beautify-css-tests' {
  declare module.exports: any;
}

declare module 'js-beautify/js/test/generated/beautify-html-tests' {
  declare module.exports: any;
}

declare module 'js-beautify/js/test/generated/beautify-javascript-tests' {
  declare module.exports: any;
}

declare module 'js-beautify/js/test/node-beautify-html-perf-tests' {
  declare module.exports: any;
}

declare module 'js-beautify/js/test/node-beautify-perf-tests' {
  declare module.exports: any;
}

declare module 'js-beautify/js/test/node-beautify-tests' {
  declare module.exports: any;
}

declare module 'js-beautify/js/test/resources/editorconfig/example-base' {
  declare module.exports: any;
}

declare module 'js-beautify/js/test/resources/example1' {
  declare module.exports: any;
}

declare module 'js-beautify/js/test/sanitytest' {
  declare module.exports: any;
}

declare module 'js-beautify/test/data/css/tests' {
  declare module.exports: any;
}

declare module 'js-beautify/test/data/html/tests' {
  declare module.exports: any;
}

declare module 'js-beautify/test/data/javascript/inputlib' {
  declare module.exports: any;
}

declare module 'js-beautify/test/data/javascript/tests' {
  declare module.exports: any;
}

declare module 'js-beautify/test/generate-tests' {
  declare module.exports: any;
}

declare module 'js-beautify/test/underscore-min' {
  declare module.exports: any;
}

declare module 'js-beautify/test/underscore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-beautify/js/bin/css-beautify.js' {
  declare module.exports: $Exports<'js-beautify/js/bin/css-beautify'>;
}
declare module 'js-beautify/js/bin/html-beautify.js' {
  declare module.exports: $Exports<'js-beautify/js/bin/html-beautify'>;
}
declare module 'js-beautify/js/bin/js-beautify.js' {
  declare module.exports: $Exports<'js-beautify/js/bin/js-beautify'>;
}
declare module 'js-beautify/js/index.js' {
  declare module.exports: $Exports<'js-beautify/js/index'>;
}
declare module 'js-beautify/js/lib/beautify-css.js' {
  declare module.exports: $Exports<'js-beautify/js/lib/beautify-css'>;
}
declare module 'js-beautify/js/lib/beautify-html.js' {
  declare module.exports: $Exports<'js-beautify/js/lib/beautify-html'>;
}
declare module 'js-beautify/js/lib/beautify.js' {
  declare module.exports: $Exports<'js-beautify/js/lib/beautify'>;
}
declare module 'js-beautify/js/lib/cli.js' {
  declare module.exports: $Exports<'js-beautify/js/lib/cli'>;
}
declare module 'js-beautify/js/lib/unpackers/javascriptobfuscator_unpacker.js' {
  declare module.exports: $Exports<'js-beautify/js/lib/unpackers/javascriptobfuscator_unpacker'>;
}
declare module 'js-beautify/js/lib/unpackers/myobfuscate_unpacker.js' {
  declare module.exports: $Exports<'js-beautify/js/lib/unpackers/myobfuscate_unpacker'>;
}
declare module 'js-beautify/js/lib/unpackers/p_a_c_k_e_r_unpacker.js' {
  declare module.exports: $Exports<'js-beautify/js/lib/unpackers/p_a_c_k_e_r_unpacker'>;
}
declare module 'js-beautify/js/lib/unpackers/urlencode_unpacker.js' {
  declare module.exports: $Exports<'js-beautify/js/lib/unpackers/urlencode_unpacker'>;
}
declare module 'js-beautify/js/test/amd-beautify-tests.js' {
  declare module.exports: $Exports<'js-beautify/js/test/amd-beautify-tests'>;
}
declare module 'js-beautify/js/test/generated/beautify-css-tests.js' {
  declare module.exports: $Exports<'js-beautify/js/test/generated/beautify-css-tests'>;
}
declare module 'js-beautify/js/test/generated/beautify-html-tests.js' {
  declare module.exports: $Exports<'js-beautify/js/test/generated/beautify-html-tests'>;
}
declare module 'js-beautify/js/test/generated/beautify-javascript-tests.js' {
  declare module.exports: $Exports<'js-beautify/js/test/generated/beautify-javascript-tests'>;
}
declare module 'js-beautify/js/test/node-beautify-html-perf-tests.js' {
  declare module.exports: $Exports<'js-beautify/js/test/node-beautify-html-perf-tests'>;
}
declare module 'js-beautify/js/test/node-beautify-perf-tests.js' {
  declare module.exports: $Exports<'js-beautify/js/test/node-beautify-perf-tests'>;
}
declare module 'js-beautify/js/test/node-beautify-tests.js' {
  declare module.exports: $Exports<'js-beautify/js/test/node-beautify-tests'>;
}
declare module 'js-beautify/js/test/resources/editorconfig/example-base.js' {
  declare module.exports: $Exports<'js-beautify/js/test/resources/editorconfig/example-base'>;
}
declare module 'js-beautify/js/test/resources/example1.js' {
  declare module.exports: $Exports<'js-beautify/js/test/resources/example1'>;
}
declare module 'js-beautify/js/test/sanitytest.js' {
  declare module.exports: $Exports<'js-beautify/js/test/sanitytest'>;
}
declare module 'js-beautify/test/data/css/tests.js' {
  declare module.exports: $Exports<'js-beautify/test/data/css/tests'>;
}
declare module 'js-beautify/test/data/html/tests.js' {
  declare module.exports: $Exports<'js-beautify/test/data/html/tests'>;
}
declare module 'js-beautify/test/data/javascript/inputlib.js' {
  declare module.exports: $Exports<'js-beautify/test/data/javascript/inputlib'>;
}
declare module 'js-beautify/test/data/javascript/tests.js' {
  declare module.exports: $Exports<'js-beautify/test/data/javascript/tests'>;
}
declare module 'js-beautify/test/generate-tests.js' {
  declare module.exports: $Exports<'js-beautify/test/generate-tests'>;
}
declare module 'js-beautify/test/underscore-min.js' {
  declare module.exports: $Exports<'js-beautify/test/underscore-min'>;
}
declare module 'js-beautify/test/underscore.js' {
  declare module.exports: $Exports<'js-beautify/test/underscore'>;
}
