// flow-typed signature: 262f4231c4678b123345e988a68c7719
// flow-typed version: <<STUB>>/string-replace-loader_v^1.0.5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-replace-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-replace-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'string-replace-loader/index' {
  declare module.exports: $Exports<'string-replace-loader'>;
}
declare module 'string-replace-loader/index.js' {
  declare module.exports: $Exports<'string-replace-loader'>;
}
