// flow-typed signature: 2abaac0748f964c58e11c2c730623c50
// flow-typed version: <<STUB>>/vhost_v^3.0.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vhost'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vhost' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vhost/index' {
  declare module.exports: $Exports<'vhost'>;
}
declare module 'vhost/index.js' {
  declare module.exports: $Exports<'vhost'>;
}
